# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718b8d0007faaab3e1b982cc962a7fb455b328a498cbae6c4aa8ffc56b11fb816d5ecacddf0f9fb6f0f1de2bc5263e6e430f0de24b3003419cff39e88355f19a

test:
  secret_key_base: b6656074d2c10a368ee8a85945f21ceffc3058a3feda4ff0d2c2b863a6aed08ca06b5267afebdef5e49880415eaf79f6e2d01780787cf00db589eeeea84cf68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
